snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(resolve:REDIS_URL)%'
            logging: false
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%env(resolve:REDIS_URL)%'
            logging: false
    # configure doctrine caching
    doctrine:
        result_cache:
            client: doctrine
            entity_manager: [default]
        query_cache:
            client: doctrine
            entity_manager: default
    session:
        client: default
        locking: false
