snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: '%env(resolve:REDIS_URL)%'
            logging: false
        doctrine:
            type: predis
            alias: doctrine
            dsn: '%env(resolve:REDIS_URL)%'
            logging: false
    session:
        client: default
        locking: false
