<?php

namespace AppBundle\Repository;

/**
 * SlaveGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlaveGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
