<?php

namespace App\Repository;

/**
 * AlertDestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertDestinationRepository extends \Doctrine\ORM\EntityRepository
{
}
