<?php

namespace App\Repository;

/**
 * ProbeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProbeRepository extends \Doctrine\ORM\EntityRepository
{
}
