<?php

namespace App\Repository;

/**
 * ProbeArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProbeArchiveRepository extends \Doctrine\ORM\EntityRepository
{
}
