<?php

namespace App\Repository;

/**
 * SlaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlaveRepository extends \Doctrine\ORM\EntityRepository
{
}
