<?php

namespace App\Repository;

use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMException;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\Security\Core\User\PasswordUpgraderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ServiceEntityRepository implements PasswordUpgraderInterface
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
    }

    /**
     * Seamlessly upgrade loaded users.
     *
     * This works in combination with the providers.user.entity configuration in security.yaml.
     *
     * @param UserInterface $user
     * @param string $newEncodedPassword
     * @throws ORMException
     * @throws OptimisticLockException
     *
     * @codeCoverageIgnore
     */
    public function upgradePassword(UserInterface $user, string $newEncodedPassword): void
    {
        if (method_exists($user, 'setPassword')) {
            $user->setPassword($newEncodedPassword);
            $this->getEntityManager()->flush();
        }
    }
}
