monolog:
    channel: ['alert']
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        alert:
            type: stream
            path:  "%kernel.logs_dir%/alert.%kernel.environment%.log"
            level: info
            channels: [alert]